name: Publish to NPM

"on":
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'package.json'

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run type check
        run: npm run type-check
        
      - name: Build project
        run: npm run build
        
      - name: Check if version changed
        id: version-check
        run: |
          CURRENT_VERSION=$(npm view bun-serverless version 2>/dev/null || echo "0.0.0")
          PACKAGE_VERSION=$(node -p "require('./package.json').version")
          echo "current-version=$CURRENT_VERSION" >> $GITHUB_OUTPUT
          echo "package-version=$PACKAGE_VERSION" >> $GITHUB_OUTPUT
          if [ "$CURRENT_VERSION" != "$PACKAGE_VERSION" ]; then
            echo "version-changed=true" >> $GITHUB_OUTPUT
          else
            echo "version-changed=false" >> $GITHUB_OUTPUT
          fi
        
      - name: Publish to NPM
        if: steps.version-check.outputs.version-changed == 'true'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          
      - name: Skip publish - version unchanged
        if: steps.version-check.outputs.version-changed == 'false'
        run: |
          echo "Package version ${{ steps.version-check.outputs.package-version }} already exists on NPM"
          echo "Skipping publish step"